"""initial schema 5 pillars core

Revision ID: d8ddd3948ee0
Revises:
Create Date: 2026-06-16 15:55:44.576808
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d8ddd3948ee0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("tool_version", sa.String(length=32), nullable=False),
        sa.Column("signal_schema_version", sa.Integer(), nullable=False),
        sa.Column("config_digest", sa.String(length=64), nullable=True),
        sa.Column("pillars_requested", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("score_global", sa.Float(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["domain_id"], ["domain.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_domain_id"), "audit", ["domain_id"], unique=False)
    op.create_table(
        "aso_readiness",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("readiness_level", sa.String(length=16), nullable=False),
        sa.Column("agent_ready", sa.Boolean(), nullable=False),
        sa.Column("has_webmcp", sa.Boolean(), nullable=False),
        sa.Column("has_action_schema", sa.Boolean(), nullable=False),
        sa.Column("ai_discovery_endpoints", sa.Integer(), nullable=False),
        sa.Column("has_nlweb", sa.Boolean(), nullable=False),
        sa.Column("brand_coherence_score", sa.Numeric(), nullable=True),
        sa.Column("blocked_agent_bots", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["audit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aso_readiness_audit_id"), "aso_readiness", ["audit_id"], unique=True)
    op.create_table(
        "criterion_result",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("criterion_key", sa.String(length=64), nullable=False),
        sa.Column("pillars", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("raw_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("threshold", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["audit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_criterion_result_audit_id"), "criterion_result", ["audit_id"], unique=False
    )
    op.create_table(
        "issue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("criterion_key", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("effort", sa.Integer(), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("priority_bucket", sa.String(length=4), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("affected_pages", sa.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["audit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issue_audit_id"), "issue", ["audit_id"], unique=False)
    op.create_table(
        "page",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("render_mode", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["audit_id"], ["audit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_audit_id"), "page", ["audit_id"], unique=False)
    op.create_table(
        "pillar_score",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("pillar", sa.String(length=8), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("measured", sa.Integer(), nullable=False),
        sa.Column("excluded", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["audit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pillar_score_audit_id"), "pillar_score", ["audit_id"], unique=False)
    op.create_table(
        "page_signal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("signal_schema_version", sa.Integer(), nullable=False),
        sa.Column("internal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("external", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["page.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_signal_page_id"), "page_signal", ["page_id"], unique=False)
    # ### end Alembic commands ###

    # Index composites recommandés (document 05, §6) — non détectés par autogenerate.
    op.create_index("ix_audit_domain_started", "audit", ["domain_id", "started_at"], unique=False)
    op.create_index("ix_page_audit_render", "page", ["audit_id", "render_mode"], unique=False)
    op.create_index(
        "ix_criterion_audit_key", "criterion_result", ["audit_id", "criterion_key"], unique=False
    )
    op.create_index(
        "ix_criterion_audit_status", "criterion_result", ["audit_id", "status"], unique=False
    )
    op.create_index("ix_issue_audit_bucket", "issue", ["audit_id", "priority_bucket"], unique=False)
    op.create_index(
        "ix_issue_audit_priority", "issue", ["audit_id", "priority_score"], unique=False
    )
    op.create_index("ix_aso_readiness_level", "aso_readiness", ["readiness_level"], unique=False)
    # Index GIN sur le JSONB des signaux internes (recherche par signal).
    op.create_index(
        "ix_page_signal_internal_gin",
        "page_signal",
        ["internal"],
        unique=False,
        postgresql_using="gin",
    )


def downgrade() -> None:
    op.drop_index("ix_page_signal_internal_gin", table_name="page_signal")
    op.drop_index("ix_aso_readiness_level", table_name="aso_readiness")
    op.drop_index("ix_issue_audit_priority", table_name="issue")
    op.drop_index("ix_issue_audit_bucket", table_name="issue")
    op.drop_index("ix_criterion_audit_status", table_name="criterion_result")
    op.drop_index("ix_criterion_audit_key", table_name="criterion_result")
    op.drop_index("ix_page_audit_render", table_name="page")
    op.drop_index("ix_audit_domain_started", table_name="audit")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_signal_page_id"), table_name="page_signal")
    op.drop_table("page_signal")
    op.drop_index(op.f("ix_pillar_score_audit_id"), table_name="pillar_score")
    op.drop_table("pillar_score")
    op.drop_index(op.f("ix_page_audit_id"), table_name="page")
    op.drop_table("page")
    op.drop_index(op.f("ix_issue_audit_id"), table_name="issue")
    op.drop_table("issue")
    op.drop_index(op.f("ix_criterion_result_audit_id"), table_name="criterion_result")
    op.drop_table("criterion_result")
    op.drop_index(op.f("ix_aso_readiness_audit_id"), table_name="aso_readiness")
    op.drop_table("aso_readiness")
    op.drop_index(op.f("ix_audit_domain_id"), table_name="audit")
    op.drop_table("audit")
    op.drop_table("domain")
    # ### end Alembic commands ###
